webtalk_init -webtalk_dir D:/_University_/__AN-2__/Semestrul_2/SCID/Proiect/Proiect_PingPong/Proiect_PingPong.sim/sim_1/behav/xsim/xsim.dir/fsm_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 18 20:16:15 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94199c7d-9a0f-4a2a-a317-4ffe5d927d7b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ccd76622940048629c7c6ffd2df426c2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6436_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3734870022 -regid "" -xml D:/_University_/__AN-2__/Semestrul_2/SCID/Proiect/Proiect_PingPong/Proiect_PingPong.sim/sim_1/behav/xsim/xsim.dir/fsm_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/_University_/__AN-2__/Semestrul_2/SCID/Proiect/Proiect_PingPong/Proiect_PingPong.sim/sim_1/behav/xsim/xsim.dir/fsm_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/_University_/__AN-2__/Semestrul_2/SCID/Proiect/Proiect_PingPong/Proiect_PingPong.sim/sim_1/behav/xsim/xsim.dir/fsm_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
